Repository hsp-harut/EquipmentStylesheets, pull requests merged in 2019-04, with the labels that each got.

#3 Gevorg: Task_XML_And_XSL
  xsl/everything.xsl
  xsl/network.xsl
  xsl/nt_computers.xsl
  xsl/processor.xsl
Labels: NOT PASSED, needs work

#5 Hripsime: XML / XSL
  html/computer.html
  html/everything.html
  html/network.html
  html/processor.html
  task/.~lock.Equipment Stylesheets.doc#
  xml/equipment.xml
  xsl/everything.xsl
  xsl/network.xsl
  xsl/nt_computers.xsl
  xsl/processor.xsl
Labels: review #1

#6 Lusine:XML & XSL
  computers.html
  everything.html
  network.html
  processor.html
  xsl/everything.xsl
  xsl/network.xsl
  xsl/nt_computers.xsl
  xsl/processor.xsl
Labels: review #2
